### ISSUE TITLE
Console not working with latest libgdx v1.9.4

### ISSUE THREAD

**Issue by bladecoder** [StrongJoshua/libgdx-inGameConsole#20]
Hi!

With the latest libgdx version (1.9.4) the console doesn't work.

The stacktrace:

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.badlogic.gdx.scenes.scene2d.Stage.setKeyboardFocus(Lcom/badlogic/gdx/scenes/scene2d/Actor;)V
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:131)
Caused by: java.lang.NoSuchMethodError: com.badlogic.gdx.scenes.scene2d.Stage.setKeyboardFocus(Lcom/badlogic/gdx/scenes/scene2d/Actor;)V
	at com.strongjoshua.console.GUIConsole.<init>(GUIConsole.java:111)
	at com.strongjoshua.console.GUIConsole.<init>(GUIConsole.java:69)
	at com.strongjoshua.console.GUIConsole.<init>(GUIConsole.java:60)
	at com.bladecoder.engineeditor.Editor.create(Editor.java:151)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```

**Comment by AStrangeEnigma** [comment]
Same issue. Regardless, thanks for the awesome project!

**Comment by StrongJoshua** [comment]
Shouldn't be a hard fix. I'll take a look at it when I'm free later today, or if you're free, one of you (or anyone reading this) can submit a pull request.

**Comment by aitor3ml** [comment]
Recompiling the project after upgrading pom.xml (gdx to 1.9.4) worked for me

**Comment by StrongJoshua** [comment]
That's strange... It should download it's own 1.9.3 LibGdx jar since that's the listed dependency. Someone send a pull request if the general consensus is that that was the problem.

**Comment by StrongJoshua** [comment]
The readme is currently misleading, I apologize. I won't be able to deploy until tomorrow when I have access to my desktop with my signing secret key.

**Comment by AStrangeEnigma** [comment]
Thanks for your work! Eager to pull this in an update :)

Also, I dunno if your profile is current, but I'm a sophomore CS major as well!

**Comment by StrongJoshua** [comment]
The fix has been deployed. The newest version is **0.5.1**. Hope this resolves everyone's problems.
